# --------------------------------------
# Fahrradwetter-Konfiguration (OWM + lokal)
# --------------------------------------

# -> Abschnitt 1 & 2 wie in "sensor_openweathermap_only.yaml"

# 3. Aktuelle lokale Wetterdaten (von der Wetterstation)
- platform: template
  sensors:
    fahrradwetter_aktuell:
      friendly_name: "Fahrradwetter Aktuell"
      unit_of_measurement: "°C"
      value_template: >
        {% set local_temp = states('sensor.DEIN_SENSORNAME_temperature') | float(0) %}
        {% set owm_temp = states('sensor.fahrradwetter_heute') | float(0) %}
        {% if local_temp > 0 %}
          {{ local_temp }}
        {% else %}
          {{ owm_temp }}
        {% endif %}
      attribute_templates:
        source: >
          {% if states('sensor.DEIN_SENSORNAME_temperature') | float(0) > 0 %}
            lokal
          {% else %}
            openweathermap
          {% endif %}
        temp: >
          {{ states('sensor.DEIN_SENSORNAME_temperature') | float(0) if states('sensor.DEIN_SENSORNAME_temperature') | float(0) > 0 else states('sensor.fahrradwetter_heute') | float(0) }}
        wind: >
          {{ states('sensor.DEIN_SENSORNAME_wind') | float(0) if states('sensor.DEIN_SENSORNAME_wind') | float(0) > 0 else state_attr('sensor.fahrradwetter_heute', 'wind').speed | float(0) }}
        rain: >
          {{ states('sensor.DEIN_SENSORNAME_rain') | float(0) if states('sensor.DEIN_SENSORNAME_rain') | float(0) > 0 else state_attr('sensor.fahrradwetter_heute', 'rain')['1h'] | float(0) }}
        beurteilung: >
          {% set temp = this.attributes.temp | float(0) %}
          {% set wind = this.attributes.wind | float(0) %}
          {% set rain = this.attributes.rain | float(0) %}
          {% if temp > 10 and wind < 15 and rain == 0 %}
            ✅ Gut
          {% else %}
            ❌ Schlecht
          {% endif %}
